version: '3.7'

services:

  front:
    container_name: front-tailwind
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: mysite:latest 
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true